/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeCertResponseCubkSpdu"
 * 	found in "AcaEeCertResponseCubkSpdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AcaEeCertResponseCubkSpdu_H_
#define	_AcaEeCertResponseCubkSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-Encrypted.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AcaEeCertResponseCubkSpdu */
typedef V2XSecData_Encrypted_12P0_t	 AcaEeCertResponseCubkSpdu_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AcaEeCertResponseCubkSpdu_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AcaEeCertResponseCubkSpdu;
asn_struct_free_f AcaEeCertResponseCubkSpdu_free;
asn_struct_print_f AcaEeCertResponseCubkSpdu_print;
asn_constr_check_f AcaEeCertResponseCubkSpdu_constraint;
ber_type_decoder_f AcaEeCertResponseCubkSpdu_decode_ber;
der_type_encoder_f AcaEeCertResponseCubkSpdu_encode_der;
xer_type_decoder_f AcaEeCertResponseCubkSpdu_decode_xer;
xer_type_encoder_f AcaEeCertResponseCubkSpdu_encode_xer;
oer_type_decoder_f AcaEeCertResponseCubkSpdu_decode_oer;
oer_type_encoder_f AcaEeCertResponseCubkSpdu_encode_oer;
per_type_decoder_f AcaEeCertResponseCubkSpdu_decode_uper;
per_type_encoder_f AcaEeCertResponseCubkSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AcaEeCertResponseCubkSpdu_H_ */
#include <asn_internal.h>
