/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeCertResponseCubkSpdu"
 * 	found in "AcaEeCertResponseCubkSpdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AcaEeCertResponsePrivateSpdu_H_
#define	_AcaEeCertResponsePrivateSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-EncryptedSigned.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AcaEeCertResponsePrivateSpdu */
typedef V2XSecData_EncryptedSigned_31P0_t	 AcaEeCertResponsePrivateSpdu_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AcaEeCertResponsePrivateSpdu_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AcaEeCertResponsePrivateSpdu;
asn_struct_free_f AcaEeCertResponsePrivateSpdu_free;
asn_struct_print_f AcaEeCertResponsePrivateSpdu_print;
asn_constr_check_f AcaEeCertResponsePrivateSpdu_constraint;
ber_type_decoder_f AcaEeCertResponsePrivateSpdu_decode_ber;
der_type_encoder_f AcaEeCertResponsePrivateSpdu_encode_der;
xer_type_decoder_f AcaEeCertResponsePrivateSpdu_decode_xer;
xer_type_encoder_f AcaEeCertResponsePrivateSpdu_encode_xer;
oer_type_decoder_f AcaEeCertResponsePrivateSpdu_decode_oer;
oer_type_encoder_f AcaEeCertResponsePrivateSpdu_encode_oer;
per_type_decoder_f AcaEeCertResponsePrivateSpdu_decode_uper;
per_type_encoder_f AcaEeCertResponsePrivateSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AcaEeCertResponsePrivateSpdu_H_ */
#include <asn_internal.h>
