/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeCertResponseCubkSpdu"
 * 	found in "AcaEeCertResponseCubkSpdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AcaEeCertResponsePlainSpdu_H_
#define	_AcaEeCertResponsePlainSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-Unsecured.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AcaEeCertResponsePlainSpdu */
typedef V2XSecData_Unsecured_90P0_t	 AcaEeCertResponsePlainSpdu_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AcaEeCertResponsePlainSpdu_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AcaEeCertResponsePlainSpdu;
asn_struct_free_f AcaEeCertResponsePlainSpdu_free;
asn_struct_print_f AcaEeCertResponsePlainSpdu_print;
asn_constr_check_f AcaEeCertResponsePlainSpdu_constraint;
ber_type_decoder_f AcaEeCertResponsePlainSpdu_decode_ber;
der_type_encoder_f AcaEeCertResponsePlainSpdu_encode_der;
xer_type_decoder_f AcaEeCertResponsePlainSpdu_decode_xer;
xer_type_encoder_f AcaEeCertResponsePlainSpdu_encode_xer;
oer_type_decoder_f AcaEeCertResponsePlainSpdu_decode_oer;
oer_type_encoder_f AcaEeCertResponsePlainSpdu_encode_oer;
per_type_decoder_f AcaEeCertResponsePlainSpdu_decode_uper;
per_type_encoder_f AcaEeCertResponsePlainSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AcaEeCertResponsePlainSpdu_H_ */
#include <asn_internal.h>
