/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeInterfacePdu"
 * 	found in "AcaEeInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AcaEeCertResponse_H_
#define	_AcaEeCertResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include "Time32.h"
#include "Certificate.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AcaEeCertResponse */
typedef struct AcaEeCertResponse {
	Uint8_t	 version;
	Time32_t	 generationTime;
	Certificate_t	 certificate;
	OCTET_STRING_t	*privateKeyInfo	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AcaEeCertResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcaEeCertResponse;
extern asn_SEQUENCE_specifics_t asn_SPC_AcaEeCertResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_AcaEeCertResponse_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _AcaEeCertResponse_H_ */
#include <asn_internal.h>
