/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ScmsPdu"
 * 	found in "ScmsPdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AcaLaInterfacePdu_H_
#define	_AcaLaInterfacePdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AcaLaInterfacePdu */
typedef NULL_t	 AcaLaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcaLaInterfacePdu;
asn_struct_free_f AcaLaInterfacePdu_free;
asn_struct_print_f AcaLaInterfacePdu_print;
asn_constr_check_f AcaLaInterfacePdu_constraint;
ber_type_decoder_f AcaLaInterfacePdu_decode_ber;
der_type_encoder_f AcaLaInterfacePdu_encode_der;
xer_type_decoder_f AcaLaInterfacePdu_decode_xer;
xer_type_encoder_f AcaLaInterfacePdu_encode_xer;
oer_type_decoder_f AcaLaInterfacePdu_decode_oer;
oer_type_encoder_f AcaLaInterfacePdu_encode_oer;
per_type_decoder_f AcaLaInterfacePdu_decode_uper;
per_type_encoder_f AcaLaInterfacePdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AcaLaInterfacePdu_H_ */
#include <asn_internal.h>
