/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ScmsPdu"
 * 	found in "ScmsPdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AcaMaInterfacePdu_H_
#define	_AcaMaInterfacePdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AcaMaInterfacePdu */
typedef NULL_t	 AcaMaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcaMaInterfacePdu;
asn_struct_free_f AcaMaInterfacePdu_free;
asn_struct_print_f AcaMaInterfacePdu_print;
asn_constr_check_f AcaMaInterfacePdu_constraint;
ber_type_decoder_f AcaMaInterfacePdu_decode_ber;
der_type_encoder_f AcaMaInterfacePdu_encode_der;
xer_type_decoder_f AcaMaInterfacePdu_decode_xer;
xer_type_encoder_f AcaMaInterfacePdu_encode_xer;
oer_type_decoder_f AcaMaInterfacePdu_decode_oer;
oer_type_encoder_f AcaMaInterfacePdu_encode_oer;
per_type_decoder_f AcaMaInterfacePdu_decode_uper;
per_type_encoder_f AcaMaInterfacePdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AcaMaInterfacePdu_H_ */
#include <asn_internal.h>
