/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaRaInterfacePdu"
 * 	found in "AcaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AcaRaInterfacePdu.h"

static asn_oer_constraints_t asn_OER_type_AcaRaInterfacePdu_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_AcaRaInterfacePdu_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_AcaRaInterfacePdu_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AcaRaInterfacePdu, choice.raAcaCertRequest),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RaAcaCertRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"raAcaCertRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AcaRaInterfacePdu, choice.acaRaCertResponse),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AcaRaCertResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"acaRaCertResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_AcaRaInterfacePdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* raAcaCertRequest */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* acaRaCertResponse */
};
asn_CHOICE_specifics_t asn_SPC_AcaRaInterfacePdu_specs_1 = {
	sizeof(struct AcaRaInterfacePdu),
	offsetof(struct AcaRaInterfacePdu, _asn_ctx),
	offsetof(struct AcaRaInterfacePdu, present),
	sizeof(((struct AcaRaInterfacePdu *)0)->present),
	asn_MAP_AcaRaInterfacePdu_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AcaRaInterfacePdu = {
	"AcaRaInterfacePdu",
	"AcaRaInterfacePdu",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_AcaRaInterfacePdu_constr_1, &asn_PER_type_AcaRaInterfacePdu_constr_1, CHOICE_constraint },
	asn_MBR_AcaRaInterfacePdu_1,
	2,	/* Elements count */
	&asn_SPC_AcaRaInterfacePdu_specs_1	/* Additional specs */
};

