/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaRaInterfacePdu"
 * 	found in "AcaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AcaRaCertResponseSpdu_H_
#define	_AcaRaCertResponseSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-Signed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AcaRaCertResponseSpdu */
typedef V2XSecData_Signed_32P2_t	 AcaRaCertResponseSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcaRaCertResponseSpdu;
asn_struct_free_f AcaRaCertResponseSpdu_free;
asn_struct_print_f AcaRaCertResponseSpdu_print;
asn_constr_check_f AcaRaCertResponseSpdu_constraint;
ber_type_decoder_f AcaRaCertResponseSpdu_decode_ber;
der_type_encoder_f AcaRaCertResponseSpdu_encode_der;
xer_type_decoder_f AcaRaCertResponseSpdu_decode_xer;
xer_type_encoder_f AcaRaCertResponseSpdu_encode_xer;
oer_type_decoder_f AcaRaCertResponseSpdu_decode_oer;
oer_type_encoder_f AcaRaCertResponseSpdu_encode_oer;
per_type_decoder_f AcaRaCertResponseSpdu_decode_uper;
per_type_encoder_f AcaRaCertResponseSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AcaRaCertResponseSpdu_H_ */
#include <asn_internal.h>
