/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EeRaInterfacePdu"
 * 	found in "EeRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AdditionalParams.h"

static asn_oer_constraints_t asn_OER_type_AdditionalParams_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_AdditionalParams_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_AdditionalParams_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AdditionalParams, choice.original),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ButterflyParamsOriginal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"original"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AdditionalParams, choice.unified),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ButterflyExpansion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unified"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AdditionalParams, choice.compactUnified),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ButterflyExpansion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"compactUnified"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AdditionalParams, choice.encryptionKey),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PublicEncryptionKey,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"encryptionKey"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_AdditionalParams_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* original */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* unified */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* compactUnified */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* encryptionKey */
};
asn_CHOICE_specifics_t asn_SPC_AdditionalParams_specs_1 = {
	sizeof(struct AdditionalParams),
	offsetof(struct AdditionalParams, _asn_ctx),
	offsetof(struct AdditionalParams, present),
	sizeof(((struct AdditionalParams *)0)->present),
	asn_MAP_AdditionalParams_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AdditionalParams = {
	"AdditionalParams",
	"AdditionalParams",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_AdditionalParams_constr_1, &asn_PER_type_AdditionalParams_constr_1, CHOICE_constraint },
	asn_MBR_AdditionalParams_1,
	4,	/* Elements count */
	&asn_SPC_AdditionalParams_specs_1	/* Additional specs */
};

