/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecurityBaseDataTypes"
 * 	found in "SecurityBaseDataTypes.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AidSspRange_H_
#define	_AidSspRange_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Aid.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SspRange;

/* AidSspRange */
typedef struct AidSspRange {
	Aid_t	 aid;
	struct SspRange	*sspRange	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AidSspRange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AidSspRange;
extern asn_SEQUENCE_specifics_t asn_SPC_AidSspRange_specs_1;
extern asn_TYPE_member_t asn_MBR_AidSspRange_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SspRange.h"

#endif	/* _AidSspRange_H_ */
#include <asn_internal.h>
