/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeCertResponseCubkSpdu"
 * 	found in "AcaEeCertResponseCubkSpdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CertificateChainSpdu_H_
#define	_CertificateChainSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-Unsecured.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CertificateChainSpdu */
typedef V2XSecData_Unsecured_90P0_t	 CertificateChainSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateChainSpdu;
asn_struct_free_f CertificateChainSpdu_free;
asn_struct_print_f CertificateChainSpdu_print;
asn_constr_check_f CertificateChainSpdu_constraint;
ber_type_decoder_f CertificateChainSpdu_decode_ber;
der_type_encoder_f CertificateChainSpdu_encode_der;
xer_type_decoder_f CertificateChainSpdu_decode_xer;
xer_type_encoder_f CertificateChainSpdu_encode_xer;
oer_type_decoder_f CertificateChainSpdu_decode_oer;
oer_type_encoder_f CertificateChainSpdu_encode_oer;
per_type_decoder_f CertificateChainSpdu_decode_uper;
per_type_encoder_f CertificateChainSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateChainSpdu_H_ */
#include <asn_internal.h>
