/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CertManagementPdu"
 * 	found in "CertManagementPdu.asn"
 * 	`asn1c -fcompound-names`
 */

#include "CompositeCrl.h"

static int
memb_crl_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_type_crl_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_type_crl_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_crl_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_crl_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_crl_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SecuredCrl,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_crl_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_crl_specs_2 = {
	sizeof(struct CompositeCrl__crl),
	offsetof(struct CompositeCrl__crl, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crl_2 = {
	"crl",
	"crl",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_crl_tags_2,
	sizeof(asn_DEF_crl_tags_2)
		/sizeof(asn_DEF_crl_tags_2[0]) - 1, /* 1 */
	asn_DEF_crl_tags_2,	/* Same as above */
	sizeof(asn_DEF_crl_tags_2)
		/sizeof(asn_DEF_crl_tags_2[0]), /* 2 */
	{ &asn_OER_type_crl_constr_2, &asn_PER_type_crl_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_crl_2,
	1,	/* Single element */
	&asn_SPC_crl_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CompositeCrl_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CompositeCrl, crl),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_crl_2,
		0,
		{ &asn_OER_memb_crl_constr_2, &asn_PER_memb_crl_constr_2,  memb_crl_constraint_1 },
		0, 0, /* No default value */
		"crl"
		},
};
static const ber_tlv_tag_t asn_DEF_CompositeCrl_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CompositeCrl_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* crl */
};
asn_SEQUENCE_specifics_t asn_SPC_CompositeCrl_specs_1 = {
	sizeof(struct CompositeCrl),
	offsetof(struct CompositeCrl, _asn_ctx),
	asn_MAP_CompositeCrl_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CompositeCrl = {
	"CompositeCrl",
	"CompositeCrl",
	&asn_OP_SEQUENCE,
	asn_DEF_CompositeCrl_tags_1,
	sizeof(asn_DEF_CompositeCrl_tags_1)
		/sizeof(asn_DEF_CompositeCrl_tags_1[0]), /* 1 */
	asn_DEF_CompositeCrl_tags_1,	/* Same as above */
	sizeof(asn_DEF_CompositeCrl_tags_1)
		/sizeof(asn_DEF_CompositeCrl_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CompositeCrl_1,
	1,	/* Elements count */
	&asn_SPC_CompositeCrl_specs_1	/* Additional specs */
};

