/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CrlSsp"
 * 	found in "CRLSSP.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CracaType_H_
#define	_CracaType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CracaType {
	CracaType_isCraca	= 0,
	CracaType_issuerIsCraca	= 1
} e_CracaType;

/* CracaType */
typedef long	 CracaType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CracaType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CracaType;
extern const asn_INTEGER_specifics_t asn_SPC_CracaType_specs_1;
asn_struct_free_f CracaType_free;
asn_struct_print_f CracaType_print;
asn_constr_check_f CracaType_constraint;
ber_type_decoder_f CracaType_decode_ber;
der_type_encoder_f CracaType_encode_der;
xer_type_decoder_f CracaType_decode_xer;
xer_type_encoder_f CracaType_encode_xer;
oer_type_decoder_f CracaType_decode_oer;
oer_type_encoder_f CracaType_encode_oer;
per_type_decoder_f CracaType_decode_uper;
per_type_encoder_f CracaType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CracaType_H_ */
#include <asn_internal.h>
