/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecuredCrl"
 * 	found in "CRLSecurityPacage.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CrlAid_H_
#define	_CrlAid_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Aid.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CrlAid */
typedef Aid_t	 CrlAid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CrlAid;
asn_struct_free_f CrlAid_free;
asn_struct_print_f CrlAid_print;
asn_constr_check_f CrlAid_constraint;
ber_type_decoder_f CrlAid_decode_ber;
der_type_encoder_f CrlAid_encode_der;
xer_type_decoder_f CrlAid_decode_xer;
xer_type_encoder_f CrlAid_encode_xer;
oer_type_decoder_f CrlAid_decode_oer;
oer_type_encoder_f CrlAid_encode_oer;
per_type_decoder_f CrlAid_decode_uper;
per_type_encoder_f CrlAid_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CrlAid_H_ */
#include <asn_internal.h>
