/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CrlSsp"
 * 	found in "CRLSSP.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CrlSsp_H_
#define	_CrlSsp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include "CracaType.h"
#include "PermissibleCrls.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CrlSsp */
typedef struct CrlSsp {
	Uint8_t	 version;
	CracaType_t	 associatedCraca;
	PermissibleCrls_t	 crls;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CrlSsp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CrlSsp;

#ifdef __cplusplus
}
#endif

#endif	/* _CrlSsp_H_ */
#include <asn_internal.h>
