/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeCertResponseCubkSpdu"
 * 	found in "AcaEeCertResponseCubkSpdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EeEcaCertRequestSpdu_H_
#define	_EeEcaCertRequestSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-SignedCertRequest.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EeEcaCertRequestSpdu */
typedef V2XSecData_SignedCertRequest_65P0_t	 EeEcaCertRequestSpdu_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EeEcaCertRequestSpdu_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EeEcaCertRequestSpdu;
asn_struct_free_f EeEcaCertRequestSpdu_free;
asn_struct_print_f EeEcaCertRequestSpdu_print;
asn_constr_check_f EeEcaCertRequestSpdu_constraint;
ber_type_decoder_f EeEcaCertRequestSpdu_decode_ber;
der_type_encoder_f EeEcaCertRequestSpdu_encode_der;
xer_type_decoder_f EeEcaCertRequestSpdu_decode_xer;
xer_type_encoder_f EeEcaCertRequestSpdu_encode_xer;
oer_type_decoder_f EeEcaCertRequestSpdu_decode_oer;
oer_type_encoder_f EeEcaCertRequestSpdu_encode_oer;
per_type_decoder_f EeEcaCertRequestSpdu_decode_uper;
per_type_encoder_f EeEcaCertRequestSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EeEcaCertRequestSpdu_H_ */
#include <asn_internal.h>
