/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeCertResponseCubkSpdu"
 * 	found in "AcaEeCertResponseCubkSpdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EeRaDownloadRequestSpdu_H_
#define	_EeRaDownloadRequestSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-SignedEncrypted.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EeRaDownloadRequestSpdu */
typedef V2XSecData_SignedEncrypted_82P0_t	 EeRaDownloadRequestSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EeRaDownloadRequestSpdu;
asn_struct_free_f EeRaDownloadRequestSpdu_free;
asn_struct_print_f EeRaDownloadRequestSpdu_print;
asn_constr_check_f EeRaDownloadRequestSpdu_constraint;
ber_type_decoder_f EeRaDownloadRequestSpdu_decode_ber;
der_type_encoder_f EeRaDownloadRequestSpdu_encode_der;
xer_type_decoder_f EeRaDownloadRequestSpdu_decode_xer;
xer_type_encoder_f EeRaDownloadRequestSpdu_encode_xer;
oer_type_decoder_f EeRaDownloadRequestSpdu_decode_oer;
oer_type_encoder_f EeRaDownloadRequestSpdu_encode_oer;
per_type_decoder_f EeRaDownloadRequestSpdu_decode_uper;
per_type_encoder_f EeRaDownloadRequestSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EeRaDownloadRequestSpdu_H_ */
#include <asn_internal.h>
