/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeCertResponseCubkSpdu"
 * 	found in "AcaEeCertResponseCubkSpdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EeRaCertRequestPlainSpdu_H_
#define	_EeRaCertRequestPlainSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-Unsecured.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EeRaCertRequestPlainSpdu */
typedef V2XSecData_Unsecured_90P0_t	 EeRaCertRequestPlainSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EeRaCertRequestPlainSpdu;
asn_struct_free_f EeRaCertRequestPlainSpdu_free;
asn_struct_print_f EeRaCertRequestPlainSpdu_print;
asn_constr_check_f EeRaCertRequestPlainSpdu_constraint;
ber_type_decoder_f EeRaCertRequestPlainSpdu_decode_ber;
der_type_encoder_f EeRaCertRequestPlainSpdu_encode_der;
xer_type_decoder_f EeRaCertRequestPlainSpdu_decode_xer;
xer_type_encoder_f EeRaCertRequestPlainSpdu_encode_xer;
oer_type_decoder_f EeRaCertRequestPlainSpdu_decode_oer;
oer_type_encoder_f EeRaCertRequestPlainSpdu_encode_oer;
per_type_decoder_f EeRaCertRequestPlainSpdu_decode_uper;
per_type_encoder_f EeRaCertRequestPlainSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EeRaCertRequestPlainSpdu_H_ */
#include <asn_internal.h>
