/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeCertResponseCubkSpdu"
 * 	found in "AcaEeCertResponseCubkSpdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EeRaSuccessorEnrollmentCertRequestSpdu_H_
#define	_EeRaSuccessorEnrollmentCertRequestSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-SignedEncryptedCertRequest.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EeRaSuccessorEnrollmentCertRequestSpdu */
typedef V2XSecData_SignedEncryptedCertRequest_89P0_t	 EeRaSuccessorEnrollmentCertRequestSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EeRaSuccessorEnrollmentCertRequestSpdu;
asn_struct_free_f EeRaSuccessorEnrollmentCertRequestSpdu_free;
asn_struct_print_f EeRaSuccessorEnrollmentCertRequestSpdu_print;
asn_constr_check_f EeRaSuccessorEnrollmentCertRequestSpdu_constraint;
ber_type_decoder_f EeRaSuccessorEnrollmentCertRequestSpdu_decode_ber;
der_type_encoder_f EeRaSuccessorEnrollmentCertRequestSpdu_encode_der;
xer_type_decoder_f EeRaSuccessorEnrollmentCertRequestSpdu_decode_xer;
xer_type_encoder_f EeRaSuccessorEnrollmentCertRequestSpdu_encode_xer;
oer_type_decoder_f EeRaSuccessorEnrollmentCertRequestSpdu_decode_oer;
oer_type_encoder_f EeRaSuccessorEnrollmentCertRequestSpdu_encode_oer;
per_type_decoder_f EeRaSuccessorEnrollmentCertRequestSpdu_decode_uper;
per_type_encoder_f EeRaSuccessorEnrollmentCertRequestSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EeRaSuccessorEnrollmentCertRequestSpdu_H_ */
#include <asn_internal.h>
