/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CRLBaseTypes"
 * 	found in "CRLBaseTypes.asn"
 * 	`asn1c -fcompound-names`
 */

#include "GroupSingleSeedCrlEntry.h"

asn_TYPE_member_t asn_MBR_GroupSingleSeedCrlEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GroupSingleSeedCrlEntry, iMax),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iMax"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroupSingleSeedCrlEntry, laid),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GroupSingleSeedCrlEntry, linkageSeed),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CRLBaseTypes_LinkageSeed,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"linkageSeed"
		},
};
static const ber_tlv_tag_t asn_DEF_GroupSingleSeedCrlEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GroupSingleSeedCrlEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* iMax */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* laid */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* linkageSeed */
};
asn_SEQUENCE_specifics_t asn_SPC_GroupSingleSeedCrlEntry_specs_1 = {
	sizeof(struct GroupSingleSeedCrlEntry),
	offsetof(struct GroupSingleSeedCrlEntry, _asn_ctx),
	asn_MAP_GroupSingleSeedCrlEntry_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GroupSingleSeedCrlEntry = {
	"GroupSingleSeedCrlEntry",
	"GroupSingleSeedCrlEntry",
	&asn_OP_SEQUENCE,
	asn_DEF_GroupSingleSeedCrlEntry_tags_1,
	sizeof(asn_DEF_GroupSingleSeedCrlEntry_tags_1)
		/sizeof(asn_DEF_GroupSingleSeedCrlEntry_tags_1[0]), /* 1 */
	asn_DEF_GroupSingleSeedCrlEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_GroupSingleSeedCrlEntry_tags_1)
		/sizeof(asn_DEF_GroupSingleSeedCrlEntry_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_GroupSingleSeedCrlEntry_1,
	3,	/* Elements count */
	&asn_SPC_GroupSingleSeedCrlEntry_specs_1	/* Additional specs */
};

