/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaMaInterfacePdu"
 * 	found in "LaMaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GroupLSInfo_H_
#define	_GroupLSInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IValue.h"
#include "Uint32.h"
#include "LinkageValue.h"
#include "SecurityBaseDataTypes_LinkageSeed.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GroupLSInfo */
typedef struct GroupLSInfo {
	IValue_t	 i;
	Uint32_t	 j;
	LinkageValue_t	 lv;
	SecurityBaseDataTypes_LinkageSeed_t	 ls;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GroupLSInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GroupLSInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_GroupLSInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_GroupLSInfo_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _GroupLSInfo_H_ */
#include <asn_internal.h>
