/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaRaInterfacePdu"
 * 	found in "LaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GroupLVResponseLinkageChain_H_
#define	_GroupLVResponseLinkageChain_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint32.h"
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EncryptedGroupLV;

/* Forward definitions */
typedef struct GroupLVResponseLinkageChain__values__Member {
	A_SEQUENCE_OF(struct EncryptedGroupLV) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GroupLVResponseLinkageChain__values__Member;

/* GroupLVResponseLinkageChain */
typedef struct GroupLVResponseLinkageChain {
	Uint32_t	 jMax;
	struct GroupLVResponseLinkageChain__values {
		A_SEQUENCE_OF(GroupLVResponseLinkageChain__values__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} values;
	OCTET_STRING_t	 groupIdentifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GroupLVResponseLinkageChain_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GroupLVResponseLinkageChain;
extern asn_SEQUENCE_specifics_t asn_SPC_GroupLVResponseLinkageChain_specs_1;
extern asn_TYPE_member_t asn_MBR_GroupLVResponseLinkageChain_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EncryptedGroupLV.h"

#endif	/* _GroupLVResponseLinkageChain_H_ */
#include <asn_internal.h>
