/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CRLBaseTypes"
 * 	found in "CRLBaseTypes.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GroupSingleSeedCrlEntry_H_
#define	_GroupSingleSeedCrlEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint16.h"
#include "LaId.h"
#include "CRLBaseTypes_LinkageSeed.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GroupSingleSeedCrlEntry */
typedef struct GroupSingleSeedCrlEntry {
	Uint16_t	 iMax;
	LaId_t	 laid;
	CRLBaseTypes_LinkageSeed_t	 linkageSeed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GroupSingleSeedCrlEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GroupSingleSeedCrlEntry;
extern asn_SEQUENCE_specifics_t asn_SPC_GroupSingleSeedCrlEntry_specs_1;
extern asn_TYPE_member_t asn_MBR_GroupSingleSeedCrlEntry_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _GroupSingleSeedCrlEntry_H_ */
#include <asn_internal.h>
