/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaRaInterfacePdu"
 * 	found in "LaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IndividualLVResponseLinkageChain_H_
#define	_IndividualLVResponseLinkageChain_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include "LinkageChainId.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EncryptedIndividualLV;

/* Forward definitions */
typedef struct IndividualLVResponseLinkageChain__values__Member {
	A_SEQUENCE_OF(struct EncryptedIndividualLV) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IndividualLVResponseLinkageChain__values__Member;

/* IndividualLVResponseLinkageChain */
typedef struct IndividualLVResponseLinkageChain {
	Uint8_t	 jMax;
	struct IndividualLVResponseLinkageChain__values {
		A_SEQUENCE_OF(IndividualLVResponseLinkageChain__values__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} values;
	LinkageChainId_t	 linkageChainId;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IndividualLVResponseLinkageChain_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IndividualLVResponseLinkageChain;
extern asn_SEQUENCE_specifics_t asn_SPC_IndividualLVResponseLinkageChain_specs_1;
extern asn_TYPE_member_t asn_MBR_IndividualLVResponseLinkageChain_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EncryptedIndividualLV.h"

#endif	/* _IndividualLVResponseLinkageChain_H_ */
#include <asn_internal.h>
