/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaMaInterfacePdu"
 * 	found in "LaMaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IndividualLSInfo_H_
#define	_IndividualLSInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IValue.h"
#include "LinkageValue.h"
#include "SecurityBaseDataTypes_LinkageSeed.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IndividualLSInfo */
typedef struct IndividualLSInfo {
	IValue_t	 i;
	LinkageValue_t	 lv;
	SecurityBaseDataTypes_LinkageSeed_t	 ls;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IndividualLSInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IndividualLSInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_IndividualLSInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_IndividualLSInfo_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _IndividualLSInfo_H_ */
#include <asn_internal.h>
