/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaMaInterfacePdu"
 * 	found in "LaMaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LaMaLinkageSeedResponseSpdu_H_
#define	_LaMaLinkageSeedResponseSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-SignedEncrypted.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LaMaLinkageSeedResponseSpdu */
typedef V2XSecData_SignedEncrypted_82P1_t	 LaMaLinkageSeedResponseSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaMaLinkageSeedResponseSpdu;
asn_struct_free_f LaMaLinkageSeedResponseSpdu_free;
asn_struct_print_f LaMaLinkageSeedResponseSpdu_print;
asn_constr_check_f LaMaLinkageSeedResponseSpdu_constraint;
ber_type_decoder_f LaMaLinkageSeedResponseSpdu_decode_ber;
der_type_encoder_f LaMaLinkageSeedResponseSpdu_encode_der;
xer_type_decoder_f LaMaLinkageSeedResponseSpdu_decode_xer;
xer_type_encoder_f LaMaLinkageSeedResponseSpdu_encode_xer;
oer_type_decoder_f LaMaLinkageSeedResponseSpdu_decode_oer;
oer_type_encoder_f LaMaLinkageSeedResponseSpdu_encode_oer;
per_type_decoder_f LaMaLinkageSeedResponseSpdu_decode_uper;
per_type_encoder_f LaMaLinkageSeedResponseSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LaMaLinkageSeedResponseSpdu_H_ */
#include <asn_internal.h>
