/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaMaInterfacePdu"
 * 	found in "LaMaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LaMaLinkageSeedResponse_H_
#define	_LaMaLinkageSeedResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HashedId8.h"
#include "LaId.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IndividualLSInfo;
struct GroupLSInfo;

/* LaMaLinkageSeedResponse */
typedef struct LaMaLinkageSeedResponse {
	HashedId8_t	 requestHash;
	LaId_t	 laId;
	struct LaMaLinkageSeedResponse__individualLSInfos {
		A_SEQUENCE_OF(struct IndividualLSInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} individualLSInfos;
	struct LaMaLinkageSeedResponse__groupLSInfos {
		A_SEQUENCE_OF(struct GroupLSInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} groupLSInfos;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LaMaLinkageSeedResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaMaLinkageSeedResponse;
extern asn_SEQUENCE_specifics_t asn_SPC_LaMaLinkageSeedResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_LaMaLinkageSeedResponse_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IndividualLSInfo.h"
#include "GroupLSInfo.h"

#endif	/* _LaMaLinkageSeedResponse_H_ */
#include <asn_internal.h>
