/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaMaInterfacePdu"
 * 	found in "LaMaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#include "LaMaInterfacePdu.h"

static asn_oer_constraints_t asn_OER_type_LaMaInterfacePdu_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_LaMaInterfacePdu_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_LaMaInterfacePdu_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LaMaInterfacePdu, choice.maLaLinkageSeedRequest),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MaLaLinkageSeedRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maLaLinkageSeedRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaMaInterfacePdu, choice.laMaLinkageSeedResponse),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaMaLinkageSeedResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laMaLinkageSeedResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_LaMaInterfacePdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* maLaLinkageSeedRequest */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* laMaLinkageSeedResponse */
};
asn_CHOICE_specifics_t asn_SPC_LaMaInterfacePdu_specs_1 = {
	sizeof(struct LaMaInterfacePdu),
	offsetof(struct LaMaInterfacePdu, _asn_ctx),
	offsetof(struct LaMaInterfacePdu, present),
	sizeof(((struct LaMaInterfacePdu *)0)->present),
	asn_MAP_LaMaInterfacePdu_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_LaMaInterfacePdu = {
	"LaMaInterfacePdu",
	"LaMaInterfacePdu",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_LaMaInterfacePdu_constr_1, &asn_PER_type_LaMaInterfacePdu_constr_1, CHOICE_constraint },
	asn_MBR_LaMaInterfacePdu_1,
	2,	/* Elements count */
	&asn_SPC_LaMaInterfacePdu_specs_1	/* Additional specs */
};

