/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaRaInterfacePdu"
 * 	found in "LaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#include "LaPraLinkageValueResponse.h"

static int
memb_individualLVs_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_groupLVs_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_type_individualLVs_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_type_individualLVs_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_groupLVs_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_type_groupLVs_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_individualLVs_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_individualLVs_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_groupLVs_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_groupLVs_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_individualLVs_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_IndividualLVResponseLinkageChain,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_individualLVs_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_individualLVs_specs_4 = {
	sizeof(struct LaPraLinkageValueResponse__individualLVs),
	offsetof(struct LaPraLinkageValueResponse__individualLVs, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_individualLVs_4 = {
	"individualLVs",
	"individualLVs",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_individualLVs_tags_4,
	sizeof(asn_DEF_individualLVs_tags_4)
		/sizeof(asn_DEF_individualLVs_tags_4[0]) - 1, /* 1 */
	asn_DEF_individualLVs_tags_4,	/* Same as above */
	sizeof(asn_DEF_individualLVs_tags_4)
		/sizeof(asn_DEF_individualLVs_tags_4[0]), /* 2 */
	{ &asn_OER_type_individualLVs_constr_4, &asn_PER_type_individualLVs_constr_4, SEQUENCE_OF_constraint },
	asn_MBR_individualLVs_4,
	1,	/* Single element */
	&asn_SPC_individualLVs_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_groupLVs_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GroupLVResponseLinkageChain,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_groupLVs_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_groupLVs_specs_6 = {
	sizeof(struct LaPraLinkageValueResponse__groupLVs),
	offsetof(struct LaPraLinkageValueResponse__groupLVs, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_groupLVs_6 = {
	"groupLVs",
	"groupLVs",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_groupLVs_tags_6,
	sizeof(asn_DEF_groupLVs_tags_6)
		/sizeof(asn_DEF_groupLVs_tags_6[0]) - 1, /* 1 */
	asn_DEF_groupLVs_tags_6,	/* Same as above */
	sizeof(asn_DEF_groupLVs_tags_6)
		/sizeof(asn_DEF_groupLVs_tags_6[0]), /* 2 */
	{ &asn_OER_type_groupLVs_constr_6, &asn_PER_type_groupLVs_constr_6, SEQUENCE_OF_constraint },
	asn_MBR_groupLVs_6,
	1,	/* Single element */
	&asn_SPC_groupLVs_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LaPraLinkageValueResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LaPraLinkageValueResponse, iMin),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iMin"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaPraLinkageValueResponse, iMax),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iMax"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaPraLinkageValueResponse, individualLVs),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_individualLVs_4,
		0,
		{ &asn_OER_memb_individualLVs_constr_4, &asn_PER_memb_individualLVs_constr_4,  memb_individualLVs_constraint_1 },
		0, 0, /* No default value */
		"individualLVs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaPraLinkageValueResponse, groupLVs),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_groupLVs_6,
		0,
		{ &asn_OER_memb_groupLVs_constr_6, &asn_PER_memb_groupLVs_constr_6,  memb_groupLVs_constraint_1 },
		0, 0, /* No default value */
		"groupLVs"
		},
};
static const ber_tlv_tag_t asn_DEF_LaPraLinkageValueResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LaPraLinkageValueResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* iMin */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* iMax */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* individualLVs */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* groupLVs */
};
asn_SEQUENCE_specifics_t asn_SPC_LaPraLinkageValueResponse_specs_1 = {
	sizeof(struct LaPraLinkageValueResponse),
	offsetof(struct LaPraLinkageValueResponse, _asn_ctx),
	asn_MAP_LaPraLinkageValueResponse_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LaPraLinkageValueResponse = {
	"LaPraLinkageValueResponse",
	"LaPraLinkageValueResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_LaPraLinkageValueResponse_tags_1,
	sizeof(asn_DEF_LaPraLinkageValueResponse_tags_1)
		/sizeof(asn_DEF_LaPraLinkageValueResponse_tags_1[0]), /* 1 */
	asn_DEF_LaPraLinkageValueResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_LaPraLinkageValueResponse_tags_1)
		/sizeof(asn_DEF_LaPraLinkageValueResponse_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LaPraLinkageValueResponse_1,
	4,	/* Elements count */
	&asn_SPC_LaPraLinkageValueResponse_specs_1	/* Additional specs */
};

