/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaRaInterfacePdu"
 * 	found in "LaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LinkageChainId_H_
#define	_LinkageChainId_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EncryptedData.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LinkageChainId */
typedef EncryptedData_t	 LinkageChainId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LinkageChainId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LinkageChainId;
asn_struct_free_f LinkageChainId_free;
asn_struct_print_f LinkageChainId_print;
asn_constr_check_f LinkageChainId_constraint;
ber_type_decoder_f LinkageChainId_decode_ber;
der_type_encoder_f LinkageChainId_encode_der;
xer_type_decoder_f LinkageChainId_decode_xer;
xer_type_encoder_f LinkageChainId_encode_xer;
oer_type_decoder_f LinkageChainId_decode_oer;
oer_type_encoder_f LinkageChainId_encode_oer;
per_type_decoder_f LinkageChainId_decode_uper;
per_type_encoder_f LinkageChainId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LinkageChainId_H_ */
#include <asn_internal.h>
