/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaMaInterfacePdu"
 * 	found in "LaMaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_MaLaLinkageSeedRequestSpdu_H_
#define	_MaLaLinkageSeedRequestSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-SignedEncrypted.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MaLaLinkageSeedRequestSpdu */
typedef V2XSecData_SignedEncrypted_82P1_t	 MaLaLinkageSeedRequestSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MaLaLinkageSeedRequestSpdu;
asn_struct_free_f MaLaLinkageSeedRequestSpdu_free;
asn_struct_print_f MaLaLinkageSeedRequestSpdu_print;
asn_constr_check_f MaLaLinkageSeedRequestSpdu_constraint;
ber_type_decoder_f MaLaLinkageSeedRequestSpdu_decode_ber;
der_type_encoder_f MaLaLinkageSeedRequestSpdu_encode_der;
xer_type_decoder_f MaLaLinkageSeedRequestSpdu_decode_xer;
xer_type_encoder_f MaLaLinkageSeedRequestSpdu_encode_xer;
oer_type_decoder_f MaLaLinkageSeedRequestSpdu_decode_oer;
oer_type_encoder_f MaLaLinkageSeedRequestSpdu_encode_oer;
per_type_decoder_f MaLaLinkageSeedRequestSpdu_decode_uper;
per_type_encoder_f MaLaLinkageSeedRequestSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MaLaLinkageSeedRequestSpdu_H_ */
#include <asn_internal.h>
