/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaMaInterfacePdu"
 * 	found in "LaMaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#include "MaLaLinkageSeedRequest.h"

static int
memb_maId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_individualLVs_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_groupLVs_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_type_individualLVs_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_type_individualLVs_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_groupLVs_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_type_groupLVs_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_maId_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..255)) */};
static asn_per_constraints_t asn_PER_memb_maId_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (SIZE(0..255)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_individualLVs_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_individualLVs_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_groupLVs_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_groupLVs_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_individualLVs_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_IndividualLV,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_individualLVs_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_individualLVs_specs_3 = {
	sizeof(struct MaLaLinkageSeedRequest__individualLVs),
	offsetof(struct MaLaLinkageSeedRequest__individualLVs, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_individualLVs_3 = {
	"individualLVs",
	"individualLVs",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_individualLVs_tags_3,
	sizeof(asn_DEF_individualLVs_tags_3)
		/sizeof(asn_DEF_individualLVs_tags_3[0]) - 1, /* 1 */
	asn_DEF_individualLVs_tags_3,	/* Same as above */
	sizeof(asn_DEF_individualLVs_tags_3)
		/sizeof(asn_DEF_individualLVs_tags_3[0]), /* 2 */
	{ &asn_OER_type_individualLVs_constr_3, &asn_PER_type_individualLVs_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_individualLVs_3,
	1,	/* Single element */
	&asn_SPC_individualLVs_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_groupLVs_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GroupLV,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_groupLVs_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_groupLVs_specs_5 = {
	sizeof(struct MaLaLinkageSeedRequest__groupLVs),
	offsetof(struct MaLaLinkageSeedRequest__groupLVs, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_groupLVs_5 = {
	"groupLVs",
	"groupLVs",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_groupLVs_tags_5,
	sizeof(asn_DEF_groupLVs_tags_5)
		/sizeof(asn_DEF_groupLVs_tags_5[0]) - 1, /* 1 */
	asn_DEF_groupLVs_tags_5,	/* Same as above */
	sizeof(asn_DEF_groupLVs_tags_5)
		/sizeof(asn_DEF_groupLVs_tags_5[0]), /* 2 */
	{ &asn_OER_type_groupLVs_constr_5, &asn_PER_type_groupLVs_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_groupLVs_5,
	1,	/* Single element */
	&asn_SPC_groupLVs_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MaLaLinkageSeedRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MaLaLinkageSeedRequest, maId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_maId_constr_2, &asn_PER_memb_maId_constr_2,  memb_maId_constraint_1 },
		0, 0, /* No default value */
		"maId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MaLaLinkageSeedRequest, individualLVs),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_individualLVs_3,
		0,
		{ &asn_OER_memb_individualLVs_constr_3, &asn_PER_memb_individualLVs_constr_3,  memb_individualLVs_constraint_1 },
		0, 0, /* No default value */
		"individualLVs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MaLaLinkageSeedRequest, groupLVs),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_groupLVs_5,
		0,
		{ &asn_OER_memb_groupLVs_constr_5, &asn_PER_memb_groupLVs_constr_5,  memb_groupLVs_constraint_1 },
		0, 0, /* No default value */
		"groupLVs"
		},
};
static const ber_tlv_tag_t asn_DEF_MaLaLinkageSeedRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MaLaLinkageSeedRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* maId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* individualLVs */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* groupLVs */
};
asn_SEQUENCE_specifics_t asn_SPC_MaLaLinkageSeedRequest_specs_1 = {
	sizeof(struct MaLaLinkageSeedRequest),
	offsetof(struct MaLaLinkageSeedRequest, _asn_ctx),
	asn_MAP_MaLaLinkageSeedRequest_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MaLaLinkageSeedRequest = {
	"MaLaLinkageSeedRequest",
	"MaLaLinkageSeedRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_MaLaLinkageSeedRequest_tags_1,
	sizeof(asn_DEF_MaLaLinkageSeedRequest_tags_1)
		/sizeof(asn_DEF_MaLaLinkageSeedRequest_tags_1[0]), /* 1 */
	asn_DEF_MaLaLinkageSeedRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_MaLaLinkageSeedRequest_tags_1)
		/sizeof(asn_DEF_MaLaLinkageSeedRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MaLaLinkageSeedRequest_1,
	3,	/* Elements count */
	&asn_SPC_MaLaLinkageSeedRequest_specs_1	/* Additional specs */
};

