/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaMaInterfacePdu"
 * 	found in "LaMaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_MaLaLinkageSeedRequest_H_
#define	_MaLaLinkageSeedRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IndividualLV;
struct GroupLV;

/* MaLaLinkageSeedRequest */
typedef struct MaLaLinkageSeedRequest {
	OCTET_STRING_t	 maId;
	struct MaLaLinkageSeedRequest__individualLVs {
		A_SEQUENCE_OF(struct IndividualLV) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} individualLVs;
	struct MaLaLinkageSeedRequest__groupLVs {
		A_SEQUENCE_OF(struct GroupLV) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} groupLVs;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MaLaLinkageSeedRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MaLaLinkageSeedRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_MaLaLinkageSeedRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_MaLaLinkageSeedRequest_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IndividualLV.h"
#include "GroupLV.h"

#endif	/* _MaLaLinkageSeedRequest_H_ */
#include <asn_internal.h>
