/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_CertificateChainSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_CompositeCrlSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EcaEeCertResponseSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaCertRequestPlainSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaCertRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaDownloadRequestPlainSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaDownloadRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaSuccessorEnrollmentCertRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_RaEeCertAckSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_RaEeCertInfoSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_RaEeEnrollmentCertAckSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_SecurityMgmtAid;
extern struct asn_TYPE_descriptor_s asn_DEF_RaAcaCertRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaRaCertResponseSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_CrlContents;
extern struct asn_TYPE_descriptor_s asn_DEF_CrlAid;
extern struct asn_TYPE_descriptor_s asn_DEF_CrlSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_RootCtl;
extern struct asn_TYPE_descriptor_s asn_DEF_PkiCtl;
extern struct asn_TYPE_descriptor_s asn_DEF_MaLaLinkageSeedRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_LaMaLinkageSeedResponseSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_PraLaIndividualLinkageValueRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_PraLaGroupLinkageValueRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_LaPraLinkageValueResponseSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_ScmsSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint3;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedId32;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedId4;
extern struct asn_TYPE_descriptor_s asn_DEF_KnownLatitude;
extern struct asn_TYPE_descriptor_s asn_DEF_UnknownLatitude;
extern struct asn_TYPE_descriptor_s asn_DEF_KnownLongitude;
extern struct asn_TYPE_descriptor_s asn_DEF_UnknownLongitude;
extern struct asn_TYPE_descriptor_s asn_DEF_SspValue;
extern struct asn_TYPE_descriptor_s asn_DEF_SspBitmask;
extern struct asn_TYPE_descriptor_s asn_DEF_Countersignature;
extern struct asn_TYPE_descriptor_s asn_DEF_ExplicitCertificate;
extern struct asn_TYPE_descriptor_s asn_DEF_Reserved;
extern struct asn_TYPE_descriptor_s asn_DEF_V2XSecData_EncryptedOpen;
extern struct asn_TYPE_descriptor_s asn_DEF_ScmsPdu_Scoped;
extern struct asn_TYPE_descriptor_s asn_DEF_SignedCertificateRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_SignerSelf;
extern struct asn_TYPE_descriptor_s asn_DEF_SignerSingleCert;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module AcaEeCertResponseCubkSpdu in AcaEeCertResponseCubkSpdu.asn */
	&asn_DEF_CertificateChainSpdu,	
	&asn_DEF_CompositeCrlSpdu,	
	&asn_DEF_EcaEeCertResponseSpdu,	
	&asn_DEF_EeRaCertRequestPlainSpdu,	
	&asn_DEF_EeRaCertRequestSpdu,	
	&asn_DEF_EeRaDownloadRequestPlainSpdu,	
	&asn_DEF_EeRaDownloadRequestSpdu,	
	&asn_DEF_EeRaSuccessorEnrollmentCertRequestSpdu,	
	&asn_DEF_RaEeCertAckSpdu,	
	&asn_DEF_RaEeCertInfoSpdu,	
	&asn_DEF_RaEeEnrollmentCertAckSpdu,	
	&asn_DEF_SecurityMgmtAid,	
	/* From module AcaRaInterfacePdu in AcaRaInterfacePdu.asn */
	&asn_DEF_RaAcaCertRequestSpdu,	
	&asn_DEF_AcaRaCertResponseSpdu,	
	/* From module CRLBaseTypes in CRLBaseTypes.asn */
	&asn_DEF_CrlContents,	
	/* From module SecuredCrl in CRLSecurityPacage.asn */
	&asn_DEF_CrlAid,	
	/* From module CrlSsp in CRLSSP.asn */
	&asn_DEF_CrlSsp,	
	/* From module CTL in CTL.asn */
	&asn_DEF_RootCtl,	
	&asn_DEF_PkiCtl,	
	/* From module LaMaInterfacePdu in LaMaInterfacePdu.asn */
	&asn_DEF_MaLaLinkageSeedRequestSpdu,	
	&asn_DEF_LaMaLinkageSeedResponseSpdu,	
	/* From module LaRaInterfacePdu in LaRaInterfacePdu.asn */
	&asn_DEF_PraLaIndividualLinkageValueRequestSpdu,	
	&asn_DEF_PraLaGroupLinkageValueRequestSpdu,	
	&asn_DEF_LaPraLinkageValueResponseSpdu,	
	/* From module ScmsSsp in ScmsSsp.asn */
	&asn_DEF_ScmsSsp,	
	/* From module SecurityBaseDataTypes in SecurityBaseDataTypes.asn */
	&asn_DEF_Uint3,	
	&asn_DEF_HashedId32,	
	&asn_DEF_HashedId4,	
	&asn_DEF_KnownLatitude,	
	&asn_DEF_UnknownLatitude,	
	&asn_DEF_KnownLongitude,	
	&asn_DEF_UnknownLongitude,	
	&asn_DEF_SspValue,	
	&asn_DEF_SspBitmask,	
	/* From module SecurityDataTypes in SecurityDataTypes.asn */
	&asn_DEF_Countersignature,	
	&asn_DEF_ExplicitCertificate,	
	&asn_DEF_Reserved,	
	/* From module V2XSecData-Encrypted in V2XSecData-Encrypted.asn */
	&asn_DEF_V2XSecData_EncryptedOpen,	
	&asn_DEF_ScmsPdu_Scoped,	
	&asn_DEF_SignedCertificateRequest,	
	&asn_DEF_SignerSelf,	
	&asn_DEF_SignerSingleCert,	
	0
};

