/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CrlSsp"
 * 	found in "CRLSSP.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PermissibleCrls_H_
#define	_PermissibleCrls_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CrlSeries.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PermissibleCrls */
typedef struct PermissibleCrls {
	A_SEQUENCE_OF(CrlSeries_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PermissibleCrls_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PermissibleCrls;
extern asn_SET_OF_specifics_t asn_SPC_PermissibleCrls_specs_1;
extern asn_TYPE_member_t asn_MBR_PermissibleCrls_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _PermissibleCrls_H_ */
#include <asn_internal.h>
