/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CTL"
 * 	found in "CTL.asn"
 * 	`asn1c -fcompound-names`
 */

#include "PkiCertInfo.h"

static int
memb_crlUrl_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 511)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_maUrl_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 511)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_crlUrl_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_crlUrl_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_maUrl_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_maUrl_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_PkiCertInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PkiCertInfo, certificate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SequenceOfCertificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certificate"
		},
	{ ATF_POINTER, 2, offsetof(struct PkiCertInfo, crlUrl),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_crlUrl_constr_3, &asn_PER_memb_crlUrl_constr_3,  memb_crlUrl_constraint_1 },
		0, 0, /* No default value */
		"crlUrl"
		},
	{ ATF_POINTER, 1, offsetof(struct PkiCertInfo, maUrl),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_maUrl_constr_4, &asn_PER_memb_maUrl_constr_4,  memb_maUrl_constraint_1 },
		0, 0, /* No default value */
		"maUrl"
		},
};
static const int asn_MAP_PkiCertInfo_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_PkiCertInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PkiCertInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* certificate */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* crlUrl */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* maUrl */
};
asn_SEQUENCE_specifics_t asn_SPC_PkiCertInfo_specs_1 = {
	sizeof(struct PkiCertInfo),
	offsetof(struct PkiCertInfo, _asn_ctx),
	asn_MAP_PkiCertInfo_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_PkiCertInfo_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PkiCertInfo = {
	"PkiCertInfo",
	"PkiCertInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_PkiCertInfo_tags_1,
	sizeof(asn_DEF_PkiCertInfo_tags_1)
		/sizeof(asn_DEF_PkiCertInfo_tags_1[0]), /* 1 */
	asn_DEF_PkiCertInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_PkiCertInfo_tags_1)
		/sizeof(asn_DEF_PkiCertInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PkiCertInfo_1,
	3,	/* Elements count */
	&asn_SPC_PkiCertInfo_specs_1	/* Additional specs */
};

