/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CTL"
 * 	found in "CTL.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PkiCertInfo_H_
#define	_PkiCertInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SequenceOfCertificate.h"
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PkiCertInfo */
typedef struct PkiCertInfo {
	SequenceOfCertificate_t	 certificate;
	UTF8String_t	*crlUrl	/* OPTIONAL */;
	UTF8String_t	*maUrl	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PkiCertInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PkiCertInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_PkiCertInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_PkiCertInfo_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PkiCertInfo_H_ */
#include <asn_internal.h>
