/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaRaInterfacePdu"
 * 	found in "LaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PraLaGroupLinkageValueRequest_H_
#define	_PraLaGroupLinkageValueRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PraLaRequestHeader.h"
#include "Uint32.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PraLaGroupLinkageValueRequest */
typedef struct PraLaGroupLinkageValueRequest {
	PraLaRequestHeader_t	 header;
	Uint32_t	 jMax;
	OCTET_STRING_t	 groupIdentifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PraLaGroupLinkageValueRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PraLaGroupLinkageValueRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_PraLaGroupLinkageValueRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_PraLaGroupLinkageValueRequest_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PraLaGroupLinkageValueRequest_H_ */
#include <asn_internal.h>
