/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaRaInterfacePdu"
 * 	found in "LaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PraLaLinkageValueRequest_H_
#define	_PraLaLinkageValueRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PraLaIndividualLinkageValueRequest.h"
#include "PraLaGroupLinkageValueRequest.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PraLaLinkageValueRequest_PR {
	PraLaLinkageValueRequest_PR_NOTHING,	/* No components present */
	PraLaLinkageValueRequest_PR_individualLVRequest,
	PraLaLinkageValueRequest_PR_groupLVRequest
} PraLaLinkageValueRequest_PR;

/* PraLaLinkageValueRequest */
typedef struct PraLaLinkageValueRequest {
	PraLaLinkageValueRequest_PR present;
	union PraLaLinkageValueRequest_u {
		PraLaIndividualLinkageValueRequest_t	 individualLVRequest;
		PraLaGroupLinkageValueRequest_t	 groupLVRequest;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PraLaLinkageValueRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PraLaLinkageValueRequest;
extern asn_CHOICE_specifics_t asn_SPC_PraLaLinkageValueRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_PraLaLinkageValueRequest_1[2];
extern asn_per_constraints_t asn_PER_type_PraLaLinkageValueRequest_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PraLaLinkageValueRequest_H_ */
#include <asn_internal.h>
