/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaRaInterfacePdu"
 * 	found in "LaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PraLaIndividualLinkageValueRequest_H_
#define	_PraLaIndividualLinkageValueRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PraLaRequestHeader.h"
#include "Uint8.h"
#include "Uint32.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LinkageChainId;

/* PraLaIndividualLinkageValueRequest */
typedef struct PraLaIndividualLinkageValueRequest {
	PraLaRequestHeader_t	 header;
	Uint8_t	 jMax;
	Uint32_t	*numberOfFreshInd	/* OPTIONAL */;
	struct PraLaIndividualLinkageValueRequest__continuationsInd {
		A_SEQUENCE_OF(struct LinkageChainId) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *continuationsInd;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PraLaIndividualLinkageValueRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PraLaIndividualLinkageValueRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_PraLaIndividualLinkageValueRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_PraLaIndividualLinkageValueRequest_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LinkageChainId.h"

#endif	/* _PraLaIndividualLinkageValueRequest_H_ */
#include <asn_internal.h>
