/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaRaInterfacePdu"
 * 	found in "LaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#include "PraLaIndividualLinkageValueRequest.h"

static asn_TYPE_member_t asn_MBR_continuationsInd_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LinkageChainId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_continuationsInd_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_continuationsInd_specs_5 = {
	sizeof(struct PraLaIndividualLinkageValueRequest__continuationsInd),
	offsetof(struct PraLaIndividualLinkageValueRequest__continuationsInd, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_continuationsInd_5 = {
	"continuationsInd",
	"continuationsInd",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_continuationsInd_tags_5,
	sizeof(asn_DEF_continuationsInd_tags_5)
		/sizeof(asn_DEF_continuationsInd_tags_5[0]) - 1, /* 1 */
	asn_DEF_continuationsInd_tags_5,	/* Same as above */
	sizeof(asn_DEF_continuationsInd_tags_5)
		/sizeof(asn_DEF_continuationsInd_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_continuationsInd_5,
	1,	/* Single element */
	&asn_SPC_continuationsInd_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PraLaIndividualLinkageValueRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PraLaIndividualLinkageValueRequest, header),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PraLaRequestHeader,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PraLaIndividualLinkageValueRequest, jMax),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"jMax"
		},
	{ ATF_POINTER, 2, offsetof(struct PraLaIndividualLinkageValueRequest, numberOfFreshInd),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"numberOfFreshInd"
		},
	{ ATF_POINTER, 1, offsetof(struct PraLaIndividualLinkageValueRequest, continuationsInd),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_continuationsInd_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"continuationsInd"
		},
};
static const int asn_MAP_PraLaIndividualLinkageValueRequest_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_PraLaIndividualLinkageValueRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PraLaIndividualLinkageValueRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* header */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* jMax */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* numberOfFreshInd */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* continuationsInd */
};
asn_SEQUENCE_specifics_t asn_SPC_PraLaIndividualLinkageValueRequest_specs_1 = {
	sizeof(struct PraLaIndividualLinkageValueRequest),
	offsetof(struct PraLaIndividualLinkageValueRequest, _asn_ctx),
	asn_MAP_PraLaIndividualLinkageValueRequest_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_PraLaIndividualLinkageValueRequest_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PraLaIndividualLinkageValueRequest = {
	"PraLaIndividualLinkageValueRequest",
	"PraLaIndividualLinkageValueRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_PraLaIndividualLinkageValueRequest_tags_1,
	sizeof(asn_DEF_PraLaIndividualLinkageValueRequest_tags_1)
		/sizeof(asn_DEF_PraLaIndividualLinkageValueRequest_tags_1[0]), /* 1 */
	asn_DEF_PraLaIndividualLinkageValueRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_PraLaIndividualLinkageValueRequest_tags_1)
		/sizeof(asn_DEF_PraLaIndividualLinkageValueRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PraLaIndividualLinkageValueRequest_1,
	4,	/* Elements count */
	&asn_SPC_PraLaIndividualLinkageValueRequest_specs_1	/* Additional specs */
};

