/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaRaInterfacePdu"
 * 	found in "LaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PraLaGroupLinkageValueRequestSpdu_H_
#define	_PraLaGroupLinkageValueRequestSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-SignedEncrypted.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PraLaGroupLinkageValueRequestSpdu */
typedef V2XSecData_SignedEncrypted_82P2_t	 PraLaGroupLinkageValueRequestSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PraLaGroupLinkageValueRequestSpdu;
asn_struct_free_f PraLaGroupLinkageValueRequestSpdu_free;
asn_struct_print_f PraLaGroupLinkageValueRequestSpdu_print;
asn_constr_check_f PraLaGroupLinkageValueRequestSpdu_constraint;
ber_type_decoder_f PraLaGroupLinkageValueRequestSpdu_decode_ber;
der_type_encoder_f PraLaGroupLinkageValueRequestSpdu_encode_der;
xer_type_decoder_f PraLaGroupLinkageValueRequestSpdu_decode_xer;
xer_type_encoder_f PraLaGroupLinkageValueRequestSpdu_encode_xer;
oer_type_decoder_f PraLaGroupLinkageValueRequestSpdu_decode_oer;
oer_type_encoder_f PraLaGroupLinkageValueRequestSpdu_encode_oer;
per_type_decoder_f PraLaGroupLinkageValueRequestSpdu_decode_uper;
per_type_encoder_f PraLaGroupLinkageValueRequestSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PraLaGroupLinkageValueRequestSpdu_H_ */
#include <asn_internal.h>
