/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LaRaInterfacePdu"
 * 	found in "LaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#include "PraLaRequestHeader.h"

asn_TYPE_member_t asn_MBR_PraLaRequestHeader_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PraLaRequestHeader, iMin),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iMin"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PraLaRequestHeader, iMax),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iMax"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PraLaRequestHeader, praId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Hostname,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"praId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PraLaRequestHeader, pcaId),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Hostname,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pcaId"
		},
};
static const ber_tlv_tag_t asn_DEF_PraLaRequestHeader_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PraLaRequestHeader_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* iMin */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* iMax */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* praId */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* pcaId */
};
asn_SEQUENCE_specifics_t asn_SPC_PraLaRequestHeader_specs_1 = {
	sizeof(struct PraLaRequestHeader),
	offsetof(struct PraLaRequestHeader, _asn_ctx),
	asn_MAP_PraLaRequestHeader_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PraLaRequestHeader = {
	"PraLaRequestHeader",
	"PraLaRequestHeader",
	&asn_OP_SEQUENCE,
	asn_DEF_PraLaRequestHeader_tags_1,
	sizeof(asn_DEF_PraLaRequestHeader_tags_1)
		/sizeof(asn_DEF_PraLaRequestHeader_tags_1[0]), /* 1 */
	asn_DEF_PraLaRequestHeader_tags_1,	/* Same as above */
	sizeof(asn_DEF_PraLaRequestHeader_tags_1)
		/sizeof(asn_DEF_PraLaRequestHeader_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PraLaRequestHeader_1,
	4,	/* Elements count */
	&asn_SPC_PraLaRequestHeader_specs_1	/* Additional specs */
};

