/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaRaInterfacePdu"
 * 	found in "AcaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RaAcaCertRequest_H_
#define	_RaAcaCertRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include "Time32.h"
#include "RaAcaCertRequestFlags.h"
#include "ToBeSignedCertificate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EncryptedIndividualLV;
struct PublicEncryptionKey;

/* RaAcaCertRequest */
typedef struct RaAcaCertRequest {
	Uint8_t	 version;
	Time32_t	 generationTime;
	RaAcaCertRequestFlags_t	 flags;
	struct EncryptedIndividualLV	*linkageInfo	/* OPTIONAL */;
	struct PublicEncryptionKey	*certEncKey	/* OPTIONAL */;
	ToBeSignedCertificate_t	 tbsCert;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RaAcaCertRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RaAcaCertRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_RaAcaCertRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_RaAcaCertRequest_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EncryptedIndividualLV.h"
#include "PublicEncryptionKey.h"

#endif	/* _RaAcaCertRequest_H_ */
#include <asn_internal.h>
