/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaRaInterfacePdu"
 * 	found in "AcaRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RaAcaCertRequestSpdu_H_
#define	_RaAcaCertRequestSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-SignedCertRequest.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RaAcaCertRequestSpdu */
typedef V2XSecData_SignedCertRequest_65P1_t	 RaAcaCertRequestSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RaAcaCertRequestSpdu;
asn_struct_free_f RaAcaCertRequestSpdu_free;
asn_struct_print_f RaAcaCertRequestSpdu_print;
asn_constr_check_f RaAcaCertRequestSpdu_constraint;
ber_type_decoder_f RaAcaCertRequestSpdu_decode_ber;
der_type_encoder_f RaAcaCertRequestSpdu_encode_der;
xer_type_decoder_f RaAcaCertRequestSpdu_decode_xer;
xer_type_encoder_f RaAcaCertRequestSpdu_encode_xer;
oer_type_decoder_f RaAcaCertRequestSpdu_decode_oer;
oer_type_encoder_f RaAcaCertRequestSpdu_encode_oer;
per_type_decoder_f RaAcaCertRequestSpdu_decode_uper;
per_type_encoder_f RaAcaCertRequestSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RaAcaCertRequestSpdu_H_ */
#include <asn_internal.h>
