/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeCertResponseCubkSpdu"
 * 	found in "AcaEeCertResponseCubkSpdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RaEeCertInfoSpdu_H_
#define	_RaEeCertInfoSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-Unsecured.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RaEeCertInfoSpdu */
typedef V2XSecData_Unsecured_90P0_t	 RaEeCertInfoSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RaEeCertInfoSpdu;
asn_struct_free_f RaEeCertInfoSpdu_free;
asn_struct_print_f RaEeCertInfoSpdu_print;
asn_constr_check_f RaEeCertInfoSpdu_constraint;
ber_type_decoder_f RaEeCertInfoSpdu_decode_ber;
der_type_encoder_f RaEeCertInfoSpdu_encode_der;
xer_type_decoder_f RaEeCertInfoSpdu_decode_xer;
xer_type_encoder_f RaEeCertInfoSpdu_encode_xer;
oer_type_decoder_f RaEeCertInfoSpdu_decode_oer;
oer_type_encoder_f RaEeCertInfoSpdu_encode_oer;
per_type_decoder_f RaEeCertInfoSpdu_decode_uper;
per_type_encoder_f RaEeCertInfoSpdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RaEeCertInfoSpdu_H_ */
#include <asn_internal.h>
