/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecurityDataTypes"
 * 	found in "SecurityDataTypes.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Reserved_H_
#define	_Reserved_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertificateBase.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Reserved */
typedef CertificateBase_t	 Reserved_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Reserved;
asn_struct_free_f Reserved_free;
asn_struct_print_f Reserved_print;
asn_constr_check_f Reserved_constraint;
ber_type_decoder_f Reserved_decode_ber;
der_type_encoder_f Reserved_encode_der;
xer_type_decoder_f Reserved_decode_xer;
xer_type_encoder_f Reserved_encode_xer;
oer_type_decoder_f Reserved_decode_oer;
oer_type_encoder_f Reserved_encode_oer;
per_type_decoder_f Reserved_decode_uper;
per_type_encoder_f Reserved_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Reserved_H_ */
#include <asn_internal.h>
