/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CTL"
 * 	found in "CTL.asn"
 * 	`asn1c -fcompound-names`
 */

#include "RootCtl.h"

static asn_TYPE_member_t asn_MBR_RootCtl_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RootCtl, toBeSignedRootCtl),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ToBeSignedRootCtl,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"toBeSignedRootCtl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RootCtl, signature),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Signature,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signature"
		},
};
static const ber_tlv_tag_t asn_DEF_RootCtl_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RootCtl_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* toBeSignedRootCtl */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* signature */
};
static asn_SEQUENCE_specifics_t asn_SPC_RootCtl_specs_1 = {
	sizeof(struct RootCtl),
	offsetof(struct RootCtl, _asn_ctx),
	asn_MAP_RootCtl_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RootCtl = {
	"RootCtl",
	"RootCtl",
	&asn_OP_SEQUENCE,
	asn_DEF_RootCtl_tags_1,
	sizeof(asn_DEF_RootCtl_tags_1)
		/sizeof(asn_DEF_RootCtl_tags_1[0]), /* 1 */
	asn_DEF_RootCtl_tags_1,	/* Same as above */
	sizeof(asn_DEF_RootCtl_tags_1)
		/sizeof(asn_DEF_RootCtl_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RootCtl_1,
	2,	/* Elements count */
	&asn_SPC_RootCtl_specs_1	/* Additional specs */
};

