/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "V2XSecData-Encrypted"
 * 	found in "V2XSecData-Encrypted.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ScmsPdu_Scoped_H_
#define	_ScmsPdu_Scoped_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ScmsPdu.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ScmsPdu-Scoped */
typedef ScmsPdu_t	 ScmsPdu_Scoped_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScmsPdu_Scoped;
asn_struct_free_f ScmsPdu_Scoped_free;
asn_struct_print_f ScmsPdu_Scoped_print;
asn_constr_check_f ScmsPdu_Scoped_constraint;
ber_type_decoder_f ScmsPdu_Scoped_decode_ber;
der_type_encoder_f ScmsPdu_Scoped_encode_der;
xer_type_decoder_f ScmsPdu_Scoped_decode_xer;
xer_type_encoder_f ScmsPdu_Scoped_encode_xer;
oer_type_decoder_f ScmsPdu_Scoped_decode_oer;
oer_type_encoder_f ScmsPdu_Scoped_encode_oer;
per_type_decoder_f ScmsPdu_Scoped_decode_uper;
per_type_encoder_f ScmsPdu_Scoped_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ScmsPdu_Scoped_H_ */
#include <asn_internal.h>
