/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecurityBaseDataTypes"
 * 	found in "SecurityBaseDataTypes.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SecurityBaseDataTypes_LinkageSeed_H_
#define	_SecurityBaseDataTypes_LinkageSeed_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LinkageSeed */
typedef OCTET_STRING_t	 SecurityBaseDataTypes_LinkageSeed_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SecurityBaseDataTypes_LinkageSeed_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SecurityBaseDataTypes_LinkageSeed;
asn_struct_free_f SecurityBaseDataTypes_LinkageSeed_free;
asn_struct_print_f SecurityBaseDataTypes_LinkageSeed_print;
asn_constr_check_f SecurityBaseDataTypes_LinkageSeed_constraint;
ber_type_decoder_f SecurityBaseDataTypes_LinkageSeed_decode_ber;
der_type_encoder_f SecurityBaseDataTypes_LinkageSeed_encode_der;
xer_type_decoder_f SecurityBaseDataTypes_LinkageSeed_decode_xer;
xer_type_encoder_f SecurityBaseDataTypes_LinkageSeed_encode_xer;
oer_type_decoder_f SecurityBaseDataTypes_LinkageSeed_decode_oer;
oer_type_encoder_f SecurityBaseDataTypes_LinkageSeed_encode_oer;
per_type_decoder_f SecurityBaseDataTypes_LinkageSeed_decode_uper;
per_type_encoder_f SecurityBaseDataTypes_LinkageSeed_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityBaseDataTypes_LinkageSeed_H_ */
#include <asn_internal.h>
