/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AcaEeCertResponseCubkSpdu"
 * 	found in "AcaEeCertResponseCubkSpdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SecurityMgmtAid_H_
#define	_SecurityMgmtAid_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Aid.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SecurityMgmtAid */
typedef Aid_t	 SecurityMgmtAid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityMgmtAid;
asn_struct_free_f SecurityMgmtAid_free;
asn_struct_print_f SecurityMgmtAid_print;
asn_constr_check_f SecurityMgmtAid_constraint;
ber_type_decoder_f SecurityMgmtAid_decode_ber;
der_type_encoder_f SecurityMgmtAid_encode_der;
xer_type_decoder_f SecurityMgmtAid_decode_xer;
xer_type_encoder_f SecurityMgmtAid_encode_xer;
oer_type_decoder_f SecurityMgmtAid_decode_oer;
oer_type_encoder_f SecurityMgmtAid_encode_oer;
per_type_decoder_f SecurityMgmtAid_decode_uper;
per_type_encoder_f SecurityMgmtAid_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityMgmtAid_H_ */
#include <asn_internal.h>
