/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EeRaInterfacePdu"
 * 	found in "EeRaInterfacePdu.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SequenceOfAaaAuthorizationInfo_H_
#define	_SequenceOfAaaAuthorizationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AaaAuthorizationInfo;

/* SequenceOfAaaAuthorizationInfo */
typedef struct SequenceOfAaaAuthorizationInfo {
	A_SEQUENCE_OF(struct AaaAuthorizationInfo) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfAaaAuthorizationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfAaaAuthorizationInfo;
extern asn_SET_OF_specifics_t asn_SPC_SequenceOfAaaAuthorizationInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SequenceOfAaaAuthorizationInfo_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AaaAuthorizationInfo.h"

#endif	/* _SequenceOfAaaAuthorizationInfo_H_ */
#include <asn_internal.h>
