/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecurityBaseDataTypes"
 * 	found in "SecurityBaseDataTypes.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SequenceOfAid_H_
#define	_SequenceOfAid_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Aid.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceOfAid */
typedef struct SequenceOfAid {
	A_SEQUENCE_OF(Aid_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfAid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfAid;
extern asn_SET_OF_specifics_t asn_SPC_SequenceOfAid_specs_1;
extern asn_TYPE_member_t asn_MBR_SequenceOfAid_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceOfAid_H_ */
#include <asn_internal.h>
