/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecurityBaseDataTypes"
 * 	found in "SecurityBaseDataTypes.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SequenceOfAidSsp_H_
#define	_SequenceOfAidSsp_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AidSsp;

/* SequenceOfAidSsp */
typedef struct SequenceOfAidSsp {
	A_SEQUENCE_OF(struct AidSsp) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfAidSsp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfAidSsp;
extern asn_SET_OF_specifics_t asn_SPC_SequenceOfAidSsp_specs_1;
extern asn_TYPE_member_t asn_MBR_SequenceOfAidSsp_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AidSsp.h"

#endif	/* _SequenceOfAidSsp_H_ */
#include <asn_internal.h>
