/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CTL"
 * 	found in "CTL.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SequenceOfPkiCtlInfo_H_
#define	_SequenceOfPkiCtlInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PkiCtlInfo;

/* SequenceOfPkiCtlInfo */
typedef struct SequenceOfPkiCtlInfo {
	A_SEQUENCE_OF(struct PkiCtlInfo) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfPkiCtlInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfPkiCtlInfo;
extern asn_SET_OF_specifics_t asn_SPC_SequenceOfPkiCtlInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SequenceOfPkiCtlInfo_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PkiCtlInfo.h"

#endif	/* _SequenceOfPkiCtlInfo_H_ */
#include <asn_internal.h>
