/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CRLBaseTypes"
 * 	found in "CRLBaseTypes.asn"
 * 	`asn1c -fcompound-names`
 */

#include "SequenceOfLinkageSeed.h"

asn_TYPE_member_t asn_MBR_SequenceOfLinkageSeed_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_CRLBaseTypes_LinkageSeed,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_SequenceOfLinkageSeed_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_SequenceOfLinkageSeed_specs_1 = {
	sizeof(struct SequenceOfLinkageSeed),
	offsetof(struct SequenceOfLinkageSeed, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_SequenceOfLinkageSeed = {
	"SequenceOfLinkageSeed",
	"SequenceOfLinkageSeed",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_SequenceOfLinkageSeed_tags_1,
	sizeof(asn_DEF_SequenceOfLinkageSeed_tags_1)
		/sizeof(asn_DEF_SequenceOfLinkageSeed_tags_1[0]), /* 1 */
	asn_DEF_SequenceOfLinkageSeed_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceOfLinkageSeed_tags_1)
		/sizeof(asn_DEF_SequenceOfLinkageSeed_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_SequenceOfLinkageSeed_1,
	1,	/* Single element */
	&asn_SPC_SequenceOfLinkageSeed_specs_1	/* Additional specs */
};

