/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "V2XSecData-Encrypted"
 * 	found in "V2XSecData-Encrypted.asn"
 * 	`asn1c -fcompound-names`
 */

#include "SignedCertificateRequest.h"

static asn_TYPE_member_t asn_MBR_SignedCertificateRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignedCertificateRequest, hashId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HashAlgorithm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignedCertificateRequest, tbsRequest),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ScopedCertificateRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tbsRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignedCertificateRequest, signer),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SignerIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignedCertificateRequest, signature),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Signature,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signature"
		},
};
static const ber_tlv_tag_t asn_DEF_SignedCertificateRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SignedCertificateRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* hashId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tbsRequest */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* signer */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* signature */
};
static asn_SEQUENCE_specifics_t asn_SPC_SignedCertificateRequest_specs_1 = {
	sizeof(struct SignedCertificateRequest),
	offsetof(struct SignedCertificateRequest, _asn_ctx),
	asn_MAP_SignedCertificateRequest_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SignedCertificateRequest = {
	"SignedCertificateRequest",
	"SignedCertificateRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_SignedCertificateRequest_tags_1,
	sizeof(asn_DEF_SignedCertificateRequest_tags_1)
		/sizeof(asn_DEF_SignedCertificateRequest_tags_1[0]), /* 1 */
	asn_DEF_SignedCertificateRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignedCertificateRequest_tags_1)
		/sizeof(asn_DEF_SignedCertificateRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SignedCertificateRequest_1,
	4,	/* Elements count */
	&asn_SPC_SignedCertificateRequest_specs_1	/* Additional specs */
};

