/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "V2XSecData-Encrypted"
 * 	found in "V2XSecData-Encrypted.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SignerSingleCert_H_
#define	_SignerSingleCert_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SignerIdentifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SignerSingleCert */
typedef SignerIdentifier_t	 SignerSingleCert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignerSingleCert;
asn_struct_free_f SignerSingleCert_free;
asn_struct_print_f SignerSingleCert_print;
asn_constr_check_f SignerSingleCert_constraint;
ber_type_decoder_f SignerSingleCert_decode_ber;
der_type_encoder_f SignerSingleCert_encode_der;
xer_type_decoder_f SignerSingleCert_decode_xer;
xer_type_encoder_f SignerSingleCert_encode_xer;
oer_type_decoder_f SignerSingleCert_decode_oer;
oer_type_encoder_f SignerSingleCert_encode_oer;
per_type_decoder_f SignerSingleCert_decode_uper;
per_type_encoder_f SignerSingleCert_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SignerSingleCert_H_ */
#include <asn_internal.h>
