/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CTL"
 * 	found in "CTL.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ToBeSignedRootCtl_H_
#define	_ToBeSignedRootCtl_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include "IssuerIdentifier.h"
#include "Uint16.h"
#include "Time32.h"
#include "SequenceOfPkiCtlInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ToBeSignedRootCtl */
typedef struct ToBeSignedRootCtl {
	Uint8_t	 version;
	IssuerIdentifier_t	 issuer;
	Uint16_t	 series;
	Time32_t	 issueDate;
	Time32_t	 nextRootCtl;
	SequenceOfPkiCtlInfo_t	 pkiCtlInfoList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ToBeSignedRootCtl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ToBeSignedRootCtl;
extern asn_SEQUENCE_specifics_t asn_SPC_ToBeSignedRootCtl_specs_1;
extern asn_TYPE_member_t asn_MBR_ToBeSignedRootCtl_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _ToBeSignedRootCtl_H_ */
#include <asn_internal.h>
