/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecurityDataTypes"
 * 	found in "SecurityDataTypes.asn"
 * 	`asn1c -fcompound-names`
 */

#include "V2XSecContent.h"

static asn_oer_constraints_t asn_OER_type_V2XSecContent_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_V2XSecContent_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_V2XSecContent_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct V2XSecContent, choice.unsecuredData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Opaque,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unsecuredData"
		},
	{ ATF_POINTER, 0, offsetof(struct V2XSecContent, choice.signedData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignedData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signedData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2XSecContent, choice.encryptedData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EncryptedData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"encryptedData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2XSecContent, choice.signedCertificateRequest),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Opaque,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signedCertificateRequest"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_V2XSecContent_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* unsecuredData */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* signedData */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* encryptedData */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* signedCertificateRequest */
};
asn_CHOICE_specifics_t asn_SPC_V2XSecContent_specs_1 = {
	sizeof(struct V2XSecContent),
	offsetof(struct V2XSecContent, _asn_ctx),
	offsetof(struct V2XSecContent, present),
	sizeof(((struct V2XSecContent *)0)->present),
	asn_MAP_V2XSecContent_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_V2XSecContent = {
	"V2XSecContent",
	"V2XSecContent",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_V2XSecContent_constr_1, &asn_PER_type_V2XSecContent_constr_1, CHOICE_constraint },
	asn_MBR_V2XSecContent_1,
	4,	/* Elements count */
	&asn_SPC_V2XSecContent_specs_1	/* Additional specs */
};

