/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecurityDataTypes"
 * 	found in "SecurityDataTypes.asn"
 * 	`asn1c -fcompound-names`
 */

#include "V2XSecData.h"

static int
memb_protocolVersion_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value == 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_protocolVersion_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (3..3) */,
	-1};
static asn_per_constraints_t asn_PER_memb_protocolVersion_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  3,  3 }	/* (3..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_V2XSecData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct V2XSecData, protocolVersion),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint8,
		0,
		{ &asn_OER_memb_protocolVersion_constr_2, &asn_PER_memb_protocolVersion_constr_2,  memb_protocolVersion_constraint_1 },
		0, 0, /* No default value */
		"protocolVersion"
		},
	{ ATF_POINTER, 0, offsetof(struct V2XSecData, content),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_V2XSecContent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"content"
		},
};
static const ber_tlv_tag_t asn_DEF_V2XSecData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_V2XSecData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* protocolVersion */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* content */
};
asn_SEQUENCE_specifics_t asn_SPC_V2XSecData_specs_1 = {
	sizeof(struct V2XSecData),
	offsetof(struct V2XSecData, _asn_ctx),
	asn_MAP_V2XSecData_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_V2XSecData = {
	"V2XSecData",
	"V2XSecData",
	&asn_OP_SEQUENCE,
	asn_DEF_V2XSecData_tags_1,
	sizeof(asn_DEF_V2XSecData_tags_1)
		/sizeof(asn_DEF_V2XSecData_tags_1[0]), /* 1 */
	asn_DEF_V2XSecData_tags_1,	/* Same as above */
	sizeof(asn_DEF_V2XSecData_tags_1)
		/sizeof(asn_DEF_V2XSecData_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_V2XSecData_1,
	2,	/* Elements count */
	&asn_SPC_V2XSecData_specs_1	/* Additional specs */
};

