/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "V2XSecData-Encrypted"
 * 	found in "V2XSecData-Encrypted.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_V2XSecData_EncryptedSigned_H_
#define	_V2XSecData_EncryptedSigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XSecData-Signed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* V2XSecData-EncryptedSigned */
typedef V2XSecData_Signed_32P0_t	 V2XSecData_EncryptedSigned_31P0_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_V2XSecData_EncryptedSigned_31P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_V2XSecData_EncryptedSigned_31P0;
asn_struct_free_f V2XSecData_EncryptedSigned_31P0_free;
asn_struct_print_f V2XSecData_EncryptedSigned_31P0_print;
asn_constr_check_f V2XSecData_EncryptedSigned_31P0_constraint;
ber_type_decoder_f V2XSecData_EncryptedSigned_31P0_decode_ber;
der_type_encoder_f V2XSecData_EncryptedSigned_31P0_encode_der;
xer_type_decoder_f V2XSecData_EncryptedSigned_31P0_decode_xer;
xer_type_encoder_f V2XSecData_EncryptedSigned_31P0_encode_xer;
oer_type_decoder_f V2XSecData_EncryptedSigned_31P0_decode_oer;
oer_type_encoder_f V2XSecData_EncryptedSigned_31P0_encode_oer;
per_type_decoder_f V2XSecData_EncryptedSigned_31P0_decode_uper;
per_type_encoder_f V2XSecData_EncryptedSigned_31P0_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _V2XSecData_EncryptedSigned_H_ */
#include <asn_internal.h>
